import codecs
import sys
import os

with open('./do/globals/load-filenames.do','w') as fout:
    fout.write('********************************************************************\n')
    fout.write('*  WARNING!!!                                                      *\n')
    fout.write('*  This file is automatically generated from filenames.mk.         *\n')
    fout.write('*  Any changes you make to this file will be overwritten.          *\n')
    fout.write('*  Change filenames in filenames.mk -- the makefile will propagate *\n')
    fout.write('*  the changes to the rest of the script.                          *\n')
    fout.write('********************************************************************\n')
    fout.write('\n')
    # Note that this doesn't handle multi-line stuff in makefiles, where \ is used to 
    # continue the line
    with open('./filenames.mk','r') as fin:
        for line in fin:
            if ('#' in line) or (line=='\n'):
                fout.write(line.replace('#', '*'))
            elif '=' in line:
                linarr = line.split('=')
                fout.write('global '+linarr[0]+'= "'+linarr[1].strip()+'"\n')
    fout.write('\n')
    fout.write('\n')
